// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjIVe4TnaG_k7YyZEDty_95Uk5IAoQqLA',
    appId: '1:651811922149:web:1f00b1a405b7524861b40c',
    messagingSenderId: '651811922149',
    projectId: 'cashel-de383',
    authDomain: 'cashel-de383.firebaseapp.com',
    storageBucket: 'cashel-de383.firebasestorage.app',
    measurementId: 'G-9FWT4M1EHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWGvI_zo12gQcgOg-hgC2-G6lmvCcXFOU',
    appId: '1:651811922149:android:e9a839262f3fb9f961b40c',
    messagingSenderId: '651811922149',
    projectId: 'cashel-de383',
    storageBucket: 'cashel-de383.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjIVe4TnaG_k7YyZEDty_95Uk5IAoQqLA',
    appId: '1:651811922149:web:1160438eb15cdb4c61b40c',
    messagingSenderId: '651811922149',
    projectId: 'cashel-de383',
    authDomain: 'cashel-de383.firebaseapp.com',
    storageBucket: 'cashel-de383.firebasestorage.app',
    measurementId: 'G-C24JLYPH7V',
  );

}